services:
  backend:
    ports:
      - "8000:8000"
    environment:
      FRONTEND_ORIGINS: http://localhost:5173

  frontend:
    ports:
      - "5173:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    environment:
      VITE_API_URL: http://localhost:8000

  nginx:
    profiles:
      - production
